# Generated by Django 6.0.4 on 2026-05-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_category_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
    ]
