# Generated by Django 6.0.4 on 2026-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_item_price_item_price1_item_price2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
