# Generated by Django 6.0.4 on 2026-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='shift',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
