# Generated by Django 6.0.4 on 2026-05-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_bill_edited_at_bill_is_edited_alter_bill_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_qty', models.IntegerField()),
                ('new_qty', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.item')),
            ],
        ),
    ]
